name: Test
on:
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/appsignals-e2e-eks-test.yml
    secrets: inherit
    with:
      test-cluster-name: 'e2e-canary-test'
